### ISSUE TITLE
Is s3sync re-download files if present on destination

### ISSUE THREAD

**Issue by muzammel111** [larrabee/s3sync#4]

**Comment by muzammel111** [comment]
Dear larrabee,

I appreciated, its a very good tool, can you please confirm if s3sync downloads the images and if we kill the process and start s3sync again, can its start download files from scratch or skip files from download which already present on destination. ? i have a doubt about that, as i need to sync 4TB bucket and possibility of network breakdown. 

Thanks.

**Comment by larrabee** [comment]
Hello.
The tool redownload all files because files can be modified in source storage. If you have unstable network connection you can set big `retry` and `rs` (retry sleep interval) . Something like this: `--retry 1000 --rs 10`. With this options program will try to download each file 1000 times with 10 second interval between tries.

**Comment by muzammel111** [comment]
Right, Thankyou for your quick response.
